
// This file has been generated by the GUI designer. Do not modify.

public partial class PreferencesDlg
{
	private global::Gtk.Table table1;
	private global::Gtk.Label label1;
	private global::Gtk.Label label2;
	private global::Gtk.ComboBox MultirunCombo;
	private global::Gtk.ComboBox ThCombo;
	private global::Gtk.Button buttonCancel;
	private global::Gtk.Button button5;
    
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget PreferencesDlg
		this.Name = "PreferencesDlg";
		this.Title = global::Mono.Unix.Catalog.GetString ("Execution Preferences");
		this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Internal child PreferencesDlg.VBox
		global::Gtk.VBox w1 = this.VBox;
		w1.Name = "dialog1_VBox";
		w1.BorderWidth = ((uint)(5));
		// Container child dialog1_VBox.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(20));
		this.table1.BorderWidth = ((uint)(12));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Peptide score threshold (PLGS):");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Multi-run mode:");
		this.table1.Add (this.label2);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
		w3.TopAttach = ((uint)(1));
		w3.BottomAttach = ((uint)(2));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.MultirunCombo = global::Gtk.ComboBox.NewText ();
		this.MultirunCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Peptide Voting"));
		this.MultirunCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Peptide Merging"));
		this.MultirunCombo.Name = "MultirunCombo";
		this.MultirunCombo.Active = 0;
		this.table1.Add (this.MultirunCombo);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.MultirunCombo]));
		w4.TopAttach = ((uint)(1));
		w4.BottomAttach = ((uint)(2));
		w4.LeftAttach = ((uint)(1));
		w4.RightAttach = ((uint)(2));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.ThCombo = global::Gtk.ComboBox.NewText ();
		this.ThCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Red"));
		this.ThCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Yellow"));
		this.ThCombo.AppendText (global::Mono.Unix.Catalog.GetString ("Green"));
		this.ThCombo.Name = "ThCombo";
		this.ThCombo.Active = 0;
		this.table1.Add (this.ThCombo);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1 [this.ThCombo]));
		w5.LeftAttach = ((uint)(1));
		w5.RightAttach = ((uint)(2));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		w1.Add (this.table1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(w1 [this.table1]));
		w6.Position = 0;
		w6.Expand = false;
		w6.Fill = false;
		// Internal child PreferencesDlg.ActionArea
		global::Gtk.HButtonBox w7 = this.ActionArea;
		w7.Name = "dialog1_ActionArea";
		w7.Spacing = 10;
		w7.BorderWidth = ((uint)(5));
		w7.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.buttonCancel = new global::Gtk.Button ();
		this.buttonCancel.CanDefault = true;
		this.buttonCancel.CanFocus = true;
		this.buttonCancel.Name = "buttonCancel";
		this.buttonCancel.UseStock = true;
		this.buttonCancel.UseUnderline = true;
		this.buttonCancel.Label = "gtk-execute";
		this.AddActionWidget (this.buttonCancel, 0);
		global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.buttonCancel]));
		w8.Expand = false;
		w8.Fill = false;
		// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
		this.button5 = new global::Gtk.Button ();
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseStock = true;
		this.button5.UseUnderline = true;
		this.button5.Label = "gtk-cancel";
		this.AddActionWidget (this.button5, -6);
		global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w7 [this.button5]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 463;
		this.DefaultHeight = 140;
		this.Show ();
	}
}
